sonar.projectKey=JakeRoxs_dsos_9178fbff-b3bf-4c2c-9c34-efc7eb852932
sonar.projectName=dsos
sonar.sources=.
sonar.inclusions=Source/**/*.{cpp,c,h,hpp},Source/**/*.cs,Loader/**/*.cs,Source/**/CMakeLists.txt
sonar.exclusions=**/*.java, Resources/**/*, Source/ThirdParty/**, build/**
sonar.cfamily.compile-commands=build/compile_commands.json
sonar.cfamily.threads=4
sonar.sourceEncoding=UTF-8

# Explicitly include C# project support path for SonarScanner for .NET flow
sonar.cs.opencover.reportsPaths=**/coverage.opencover.xml